spring:
  application:
    name: jpaprac
  config:
    import: secrets.yml

  datasource:
    url: 'jdbc:mysql://${ec2.public}:${ec2.port}/${ec2.db_name}'
    username: ${ec2.username}
    password: ${ec2.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace



